name: 'Build and Test'
description: 'Build, Restore, and Test'
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore
      working-directory: ./src
      run: >-
        dotnet nuget add source --username USERNAME --password ${{ secrets.GH_PACKAGES_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/tesourohq/index.json
        && dotnet restore ./Tesouro.Payments.Service.CardProcessing.sln
    - name: Build
      working-directory: ./src
      run: dotnet build --no-restore -c Release ./Tesouro.Payments.Service.CardProcessing.sln

    - name: Test
      working-directory: ./src
      run: dotnet test --no-build -c Release -l 'trx;LogFileName=${{ runner.temp }}/results.trx' ./Tesouro.Payments.Service.CardProcessing.sln

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: ${{ runner.temp }}/results.trx
        reporter: dotnet-trx
